# Compressor Configs
# Thu Apr 03 15:08:07 UTC 2025

# Lock Compressor configs from being regenerated
compressorConfigLocked = true
# Lock Compressor resources from being regenerated
compressorResourceLocked = true

# Hide Compressor's ResourcePack from the GUI
hideResourcePack = true
